FROM php:5.6-apache
# ADD . /var/www/html
# WORKDIR /var/www/html
RUN docker-php-ext-install mysql mysqli pdo pdo_mysql
# RUN sudo apt-get install mysql-server mysql-client php5-mysql
# RUN sudo apt-get install mysql-server mysql-common php7.4 php7.4-mysql
# CMD [ "php", "index.php" ]