---
apiVersion: v1
kind: Service
metadata:
  name: wrk-web-app
  namespace: default
  labels:
    app: wrk-web-app
spec:
  ports:
    - port: 5001
      protocol: TCP
      name: wrk-web-app
  selector:
    app: wrk-web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk-web-app
  namespace: default
  labels:
    app: wrk-web-app
spec:
  selector:
    matchLabels:
      app: wrk-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: wrk-web-app
    spec:
      containers:
        - name: wrk-web-app
          image: chrismarsilva/cms-tnb-web-app:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: wrk-web-nginx
  namespace: default
  labels:
    run: wrk-web-nginx
spec:
  type: LoadBalancer # #type: LoadBalancer # ExternalName # NodePort # LoadBalancer # ClusterIP
  ports:
    - port: 81
      targetPort: 81
  selector:
    run: wrk-web-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk-web-nginx
  namespace: default
spec:
  selector:
    matchLabels:
      run: wrk-web-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: wrk-web-nginx
    spec:
      containers:
        - name: wrk-web-nginx
          image: chrismarsilva/cms-tnb-web-nginx:latest
          ports:
            - containerPort: 81 # 5678 # 80
---
# apiVersion: networking.k8s.io/v1beta1 # networking.k8s.io/v1beta1 # extensions/v1beta1 # networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: wrk-web-ingress
#   namespace: default
# spec:
#   rules:
#     - host: tamonabolsa.dev.br
#       http:
#         paths:
#           - backend:
#               serviceName: wrk-web-nginx
#               servicePort: 80
# ---

