version: "3.9"

services:

  postgres:
    image: postgres:14beta2-alpine3.14
    restart: unless-stopped # always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: authServer
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      #- ./data:/var/lib/postgresql

      # adminer:
      #   image: adminer
      #   restart: always
      #   ports:
      #     - 8081:8080
