version: "3.9"
services:
  postgres:
    image: postgres:14beta2-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: authServer
    ports:
      - "5432:5432"