version: '3'

networks:
  network-web-proxy:
    driver: bridge

services:

  wrk-nginx: 
    container_name: wrk-nginx
    image: nginx:1.21.6-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./web:/var/www
      #- ./logs.error:/var/log/nginx/error.log
    ports:
      - 80:80
    depends_on:
      - wrk-web-blue-01
      - wrk-web-blue-02
      - wrk-web-green-01
      - wrk-web-green-02
    networks:
      - network-web-proxy
  
  # wrk-nginx-proxy-manager-01:
  #   container_name: wrk-nginx-proxy-manager-01
  #   image: jc21/nginx-proxy-manager:latest
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
  #   networks:
  #     - network-web-proxy

  wrk-nginx-proxy-manager-02:
    container_name: wrk-nginx-proxy-manager-02
    image: jlesage/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "8181:8181"
      - "8081:8080"
      - "4443:4443"
    volumes:
      - ./data2:/config:rw
    networks:
      - network-web-proxy

  wrk-nginx-go-access:
    container_name: wrk-nginx-go-access
    image: xavierh/goaccess-for-nginxproxymanager:develop
    restart: always
    environment:
        - TZ=America/New_York
    ports:
        - '7880:7880'
    volumes:
        #- /path/to/host/nginx/logs:/opt/log
        #- ./logs:/opt/log
        - ./data2:/opt/log
    networks:
      - network-web-proxy

  wrk-web-blue-01: 
    container_name: wrk-web-blue-01
    image: fabricioveronez/web-page:blue
    restart: always
    networks:
      - network-web-proxy

  wrk-web-blue-02: 
    container_name: wrk-web-blue-02
    image: fabricioveronez/web-page:blue
    restart: always
    networks:
      - network-web-proxy

  wrk-web-green-01: 
    container_name: wrk-web-green-01
    image: fabricioveronez/web-page:green
    restart: always
    networks:
      - network-web-proxy

  wrk-web-green-02: 
    container_name: wrk-web-green-02
    image: fabricioveronez/web-page:green
    restart: always
    networks:
      - network-web-proxy
