version: "3.1"

services:

  mysql-master:
    container_name: mysql-5.7.master
    image: mysql:5.7
    ports:
      - "4406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/mysqld.master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql/data_master:/var/lib/mysql
  
  mysql-slave:
    container_name: mysql-5.7.slave
    image: mysql:5.7
    ports:
      - "5506:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/mysqld.slave.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql/data_slave:/var/lib/mysql
