version: "3.9"

services:
  mqseries:
    image: ibmcom/mq:latest
    ports:
      - 2414:1414
      - 9443:9443
      - 9157:9157
    hostname: mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD="Admin123"
      - MQ_APP_PASSWORD="Admin123"
      - MQ_ENABLE_METRICS=true
    container_name: mqserver
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - C:\Users\chris\Desktop\CMS Docker\CMS Docker Teste IBM MQ\data:/mnt/mqm

  # worker-mq-server:
  #   hostname: "mq"
  #   #container_name: worker-mq-server
  #   container_name: mqserver
  #   image: ibmcom/mq:latest
  #   #image: ibmcom/mq:9.2.2.0-r1-s390x
  #   ports:
  #     - "2414:1414" # Queue manager
  #     - "9443:9443" # Web console
  #   environment:
  #     - LICENSE=accept
  #     - MQ_QMGR_NAME=QM1
  #     - MQ_APP_PASSWORD=passw0rd
  #     # - CHANNEL=DEV.ADMIN.SVRCONN
  #     # - IBM_MQ_HOST=localhost
  #     # - IBM_MQ_PORT=1414
  #     # - IBM_MQ_USERID=admin
  #     # - IBM_MQ_PASSWORD=passw0rd
  #     # - IBM_MQ_QUEUE=DEV.QUEUE.1
  #     # - LOG_LEVEL=INFO
  #     # - PROFILE=test
  #   stdin_open: true
  #   tty: true
  #   restart: always
  #   volumes:
  #     #- mqseries-volume:/mnt/mqm
  #     #- mqseries-volume:/var/mqm
  #     - C:\Users\chris\Desktop\CMS Docker\CMS Docker Teste IBM MQ\data:/mnt/mqm
