FROM nginx:1.19.4-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

# RUN rm /etc/nginx/nginx.conf
# COPY ./web/nginx/nginx.conf /etc/nginx/

# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./web/nginx/nginx.conf /etc/nginx/conf.d



#FROM nginx
#RUN rm /etc/nginx/conf.d/default.conf  # Remove the default nginx.conf
#COPY nginx.conf /etc/nginx/conf.d/   # Replace with our own nginx.conf