version: "3.9"

networks:
  mysql-net:
    name: mysql-net
    # external: true
    # driver: bridge

services:
  wrk-mysql:
    container_name: wrk-mysql
    image: mysql:5.6 # mysql:latest # mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: 3306
    env_file: .env
    volumes:
      - ./lib/:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - mysql-net
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #mem_limit: 2g
    #mem_reservation: 500M
    #cpus: '2'
    #cpus: '0.50'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2g
    #       #cpus: 0.5
    #       #memory: 00M
    #     reservations:
    #       cpus: '0.50'
    #       memory: 500M

  # wrk-adminer:
  #   container_name: wrk-adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   # networks:
  #   #   - mysql-net
