version: '3'

services:

  jaeger:
    container_name: 'tracing.jaeger.agent'
    image: jaegertracing/all-in-one:latest
    #image: jaegertracing/all-in-one:1.30.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
      # - "5775:5775/udp"
      # - "6831:6831/udp"
      # - "6832:6832/udp"
      # - "5778:5778"
      # - "16686:16686"
      # - "14268:14268"
      # - "9411:9411"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    labels:
        NAME: "jaeger-agent"
    restart: on-failure

