
version: "3.9"

networks:
  mariadb-net:
    name: mariadb-net
    # external: true
    # driver: bridge

services:

  wrk-mariadb:
    container_name: wrk-mariadb
    image: mariadb:latest   # mariadb:8.0.29
    restart: always
    environment:
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_USER: "root"
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
      # MARIADB_PORT: 3808
    env_file: .env
    volumes:
      - ./lib/:/var/lib/mysql/
    # ports:
    #   - "3808:3808"
    networks:
      - mariadb-net
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #mem_limit: 2g
    #mem_reservation: 500M
    #cpus: '2'
    #cpus: '0.50'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
          #cpus: 0.5
          #memory: 00M
        reservations:
          cpus: '0.50'
          memory: 500M

  # wrk-adminer:
  #   container_name: wrk-adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   # networks:
  #   #   - mysql-net

