#version: "3.8"

# networks:
#   cms-mongo-network:
#     driver: bridge

services:
  mongo:
    image: mongo:latest  # mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
      # - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    # networks:
    #   - cms-mongo-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_BASICAUTH_USERNAME: renatogroffe
      # ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      # ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    links:
      - mongo
    # networks:
    #   - cms-mongo-network

  # mongo-express-digital-ocena:
    # image: mongo-express:latest
    # restart: always
    # ports:
      # - 8082:8081
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: cms
      # ME_CONFIG_MONGODB_ADMINPASSWORD: #Chrs2387
      # ME_CONFIG_MONGODB_URL: mongodb://cms:#Chrs2387@146.190.139.130:27017/
    # networks:
    #   - cms-mongo-network
