version: '3'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
   volumes:
     - ./esdata:/usr/share/elasticsearch/data   
   container_name: elasticsearch
   ports:
     - "9200:9200"
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
         
  kibana:
   image: docker.elastic.co/kibana/kibana:7.10.2
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch   
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports: 
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 4317:4317
      - 4318:4318
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
      - COLLECTOR_OTLP_ENABLED=true
    links:
      - elasticsearch
