services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    hostname: rabbit
    container_name: rabbit
    restart: always
    ports:
      - 5672:5672 # HTTP management UI
      - 15672:15672 # The standard AMQP protocol port # communication with the web management API
      # - 25672:25672 # (erlang) communication between the nodes and CLI tool
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
