
version: '3.9'

services:

  worker-rabbit:
    hostname: "worker-rabbit"
    image: rabbitmq:3-management
    container_name: worker-rabbit
    command: rabbitmq-server
    restart: always
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "15672" ]
      interval: 3s
      timeout: 10s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"
    # expose:
    #   - 15672
    #   - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='sdfgdsgdfgdfg'
      - CLUSTERED=true
      # - RABBITMQ_NODENAME=rabbitnode@localhost
      # - RABBITMQ_USER=skipper
      # - RABBITMQ_PASSWORD=welcome1
    networks:
      - cms-tnb-web-net-back
      - cms-tnb-web-net-front
      - cms-tnb-web-net-svc
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      # - ./.docker/rabbitmq/docker.sock:/var/run/docker.sock/
      # - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      # - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      # - ./backend-rabbitmq/etc/:/etc/backend/
      # - ./backend-rabbitmq/data/:/var/lib/backend/
      # - ./backend-rabbitmq/logs/:/var/log/backend/
    labels:
      NAME: "rabbitmq1"

networks:
  cms-tnb-web-net-back:
  cms-tnb-web-net-front:
  cms-tnb-web-net-svc:
    driver: bridge