version: "3.9"

services:

  postgres:
    image:  postgres:latest # postgres:14beta2-alpine3.14
    restart: unless-stopped # always
    environment:
      POSTGRES_PASSWORD: postgres # secret
      POSTGRES_USER: postgres # root
      POSTGRES_DB: postgres # authServer
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

      # adminer:
      #   image: adminer
      #   restart: always
      #   ports:
      #     - 8081:8080
