version: '3.9'

services:
  
  jaeger:
    container_name: cms_container_jaegertracing
    image: jaegertracing/all-in-one:latest
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - jaeger-example
  
  app:
    container_name: cms_container_hello
    image: cms_image_python_hello
    build: .
    volumes:
      - .:/code # é a pasta root para onde foi copiado todo conteudo, isso esta definido no arqv Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure # on-failure # always
    environment:
      - JAEGER_SERVICE_NAME=hello_service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks:
      - jaeger-example
    depends_on:
      - jaeger

networks:
  jaeger-example: