version: "3"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
      
  mssql:
     image: "mcr.microsoft.com/mssql/server"
     ports:
       - "1433:1433"
     environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"     
