version: '3.1'

networks: 

  cms-mongo-net:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - cms-mongo-net
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      # - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - cms-mongo-net

  mongo-express-2:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cms
      ME_CONFIG_MONGODB_ADMINPASSWORD: #Chrs2387
      ME_CONFIG_MONGODB_URL: mongodb://cms:#Chrs2387@137.184.88.130:27017/
    networks: 
      - cms-mongo-net
