version: "3.9"

services:

  wrk-golang-nginx:
    image: "cms-golang-nginx:latest"
    container_name: wrk-golang-nginx
    build: "./nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    # networks:
    #   - cms-golang-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

# networks:
#   cms-golang-network:
#     driver: bridge
