version: "3"

networks:
  network-web-proxy:
    driver: bridge

services:

  wrk-web-nginx: 
    container_name: wrk-web-nginx
    #image: nginx:latest
    image: nginx:1.21.6-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf  # erro "events" directive is not allowed here in /etc/nginx/conf.d/default.conf:7
    ports:
      - 80:80
    depends_on:
      - wrk-web-blue-01
      - wrk-web-blue-02
      - wrk-web-green-01
      - wrk-web-green-02
    networks:
      - network-web-proxy

  wrk-web-blue-01: 
    container_name: wrk-web-blue-01
    image: fabricioveronez/web-page:blue
    restart: always
    networks:
      - network-web-proxy

  wrk-web-blue-02: 
    container_name: wrk-web-blue-02
    image: fabricioveronez/web-page:blue
    restart: always
    networks:
      - network-web-proxy

  wrk-web-green-01: 
    container_name: wrk-web-green-01
    image: fabricioveronez/web-page:green
    restart: always
    networks:
      - network-web-proxy

  wrk-web-green-02: 
    container_name: wrk-web-green-02
    image: fabricioveronez/web-page:green
    restart: always
    networks:
      - network-web-proxy

