version: "3.9"

services:

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass 123 --appendonly yes --save 20 1 --loglevel warning
    volumes:
      - ./data/:/data
    # environment:
    #   - REDIS_REPLICATION_MODE=master
    # networks:
    #   - cms-tnb-redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - REDIS_HOSTS=local:localhost:6379 # redis # localhost # 127.0.0.1
      - REDIS_PASSWORD=123
    ports:
      - 8082:8081
    depends_on:
      - redis
    # networks:
    #   - cms-tnb-redis

# networks:
#   cms-tnb-redis:
#     driver: bridge
